config/routes.rb
Rails.application.routes.draw do
  resources :events, :tracks

  root to: 'tracks#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :track

  validates :start_time, :end_time, :name, :track_id, presence: true
end

app/models/track.rb
class Track < ApplicationRecord
  has_many :events

  validates :name, :display_order, presence: true

  def all_events(selected_day)
    events
    .where("start_time >= ? and start_time <= ?", selected_day.beginning_of_day, selected_day.end_of_day )
    .all + alltrack_events_on_day(selected_day)
  end

  def self.standard_tracks
    Track.where.not(name: "All").order(display_order: :asc)
  end

private

  def alltrack_events_on_day(selected_day)
    Event
    .where("track_id == ? and start_time >= ? and start_time <= ?", all_track_id, selected_day.beginning_of_day, selected_day.end_of_day )
    .all
  end

  def all_track_id
    Track.where(name: "All").ids
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController

  # GET /tracks
  def index
    @offset = params[:offset].to_i || 0
    @selected_day = day(@offset)
    @tracks = Track.standard_tracks
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def track_params
      params.require(:track).permit(:start_time, :end_time, :name, :track_id, :offset)
    end

    def day(offset)
      o = offset || 0
      Event.order(start_time: :asc).first.start_time.advance(days: o)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper

  # difference of start time and midnight in seconds, converted to hours,
  # and then multiplied by the height in px of a 1-hr block, plus the height of the headers.
  def calc_position(start_time)
    (((start_time - start_time.beginning_of_day) / 3600 * 100) + 75).to_s + "px;"
  end

  def calc_height(start_time, end_time)
    ((end_time - start_time) / 3600 * 100).to_s + "px;"
  end

end

app/helpers/tracks_helper.rb
module TracksHelper

  def day_times
    %w[0:00
       0:30
       1:00
       1:30
       2:00
       2:30
       3:00
       3:30
       4:00
       4:30
       5:00
       5:30
       6:00
       6:30
       7:00
       7:30
       8:00
       8:30
       9:00
       9:30
       10:00
       10:30
       11:00
       11:30
       12:00
       12:30
       13:00
       13:30
       14:00
       14:30
       15:00
       15:30
       16:00
       16:30
       17:00
       17:30
       18:00
       18:30
       19:00
       19:30
       20:00
       20:30
       21:00
       21:30
       22:00
       22:30
       23:00
       23:30
       0:00]
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventSchedule</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tracks/_event_divs.html.erb
  <% top_position = "top: " + calc_position(event.start_time)%>
  <% event_height = "height: " + calc_height(event.start_time, event.end_time) %>
  <%= tag.div event.name, class: "event", style: top_position + event_height %>

app/views/tracks/_form.html.erb
<%= form_with(model: track, local: true) do |form| %>
  <% if track.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(track.errors.count, "error") %> prohibited this track from being saved:</h2>

      <ul>
      <% track.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tracks/_time.html.erb
  <div class='time-unit'>
    <%= time %>
  </div>

app/views/tracks/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <div class="label nav">
      <span> <%= "#{@selected_day.to_date}" %><br></span>
        <%= link_to "<-", tracks_path(offset: @offset - 1) %>
        <%= link_to "->", tracks_path(offset: @offset + 1) %>
      </div>
        <% day_times.each do |time| %> 
          <%= render partial: "time", :locals => { :time => time } %>
        <% end %>
    </div>
    <% @tracks.each do |track| %>
      <div class="col">
        <div class="label">
          <span class="label-text"><%= track.name %></span>
        </div>
        <% track.all_events(@selected_day).map do |event| %>
          <%= render partial: "event_divs", :locals => { :event => event } %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>